import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { AGENT_EVALUATION_GROUPS, RISK_CONFIG, RISK_REVIEW_STATUS_CONFIG, RISK_SOURCE_CONFIG, mockObservabilitySessions, mockTenantMonitoringData } from './data';
import { handleFetchConversationEvidence } from './actions';
import { ObservabilityRetentionNotice, feedbackBadge, scoreText } from './shared';
import { resolveTraceReturn, tracePath, tracePathWithReturn } from './routes';

const SCORE_SCOPE_LABEL: Record<string, string> = {
  trace: '整轮 Trace',
  tool_observation: 'Tool 调用',
  retriever_observation: '知识库检索',
  generation: '生成运行',
  agent: '智能体聚合',
};

const TOOL_STATUS_LABEL = {
  success: '成功',
  error: '失败',
  timeout: '超时',
} as const;

function retrieverScenario(item: { hitCount: number; contextRelevanceScore: number | null; groundednessScore: number | null }) {
  if (item.hitCount === 0) return '未命中';
  if ((item.contextRelevanceScore ?? 1) < 0.6) return '低相关命中';
  if ((item.groundednessScore ?? 1) < 0.7) return '部分证据 / 依据不足';
  return '正常命中';
}

export default function AgentObservabilityTraceDetailPage() {
  const { tenantId = '', agentId = '', sessionId = '', traceId = '' } = useParams<{ tenantId: string; agentId: string; sessionId: string; traceId: string }>();
  const navigate = useNavigate();
  const location = useLocation();
  const sessionPath = `/platform/agent-observability/tenants/${tenantId}/agents/${agentId}/sessions/${sessionId}`;
  const returnContext = resolveTraceReturn(location.search, sessionPath);
  const tenant = mockTenantMonitoringData.find((item) => item.tenantId === tenantId);
  const agent = tenant?.agents.find((item) => item.agentId === agentId);
  const session = mockObservabilitySessions.find((item) => item.tenantId === tenantId && item.agentId === agentId && item.sessionId === sessionId);
  const trace = session?.turns.find((item) => item.traceId === traceId);

  if (!tenant || !agent || !session || !trace) {
    return <div className="min-h-full bg-slate-50 p-6"><Card><CardContent className="py-10 text-center"><div className="text-sm font-medium text-slate-800">未找到该 Trace</div><Button className="mt-4" size="sm" variant="outline" onClick={() => navigate(returnContext.returnTo)}> {returnContext.returnLabel}</Button></CardContent></Card></div>;
  }

  handleFetchConversationEvidence({ tenantId, siteId: agent.siteId, agentId, sessionId });

  const traces = [...session.turns].sort((a, b) => a.turnSeq - b.turnSeq);
  const sessionSummary = session.summary ?? `${traces[0]?.input ?? '—'} / ${traces.at(-1)?.output ?? '—'}`;
  const sessionDuration = traces.reduce((total, item) => total + item.totalDurationMs, 0);
  const taskScores = traces.map((item) => item.scores.find((score) => score.code === 'task_success')?.value).filter((value): value is number => value !== null && value !== undefined);
  const sessionQuality = taskScores.length ? taskScores.reduce((total, value) => total + value, 0) / taskScores.length : null;
  const sessionTools = traces.flatMap((item) => item.toolObservations);
  const sessionRetrievers = traces.flatMap((item) => item.retrieverObservations);
  const sessionFeedback = traces.some((item) => item.userFeedback === 'down') ? 'down' : traces.some((item) => item.userFeedback === 'up') ? 'up' : 'none';
  const scoreCatalog = new Map(AGENT_EVALUATION_GROUPS
    .filter((group) => group.appliesTo === 'all' || group.appliesTo === agent.kind)
    .flatMap((group) => group.metrics)
    .map((metric) => [metric.code, metric]));
  const toolStatusCount = {
    success: trace.toolObservations.filter((item) => item.status === 'success').length,
    error: trace.toolObservations.filter((item) => item.status === 'error').length,
    timeout: trace.toolObservations.filter((item) => item.status === 'timeout').length,
  };
  const ragScenarioLabels = trace.retrieverObservations.map(retrieverScenario);
  const evidenceSummary = [
    `本轮共执行 ${trace.toolObservations.length} 次 Tool：成功 ${toolStatusCount.success}、失败 ${toolStatusCount.error}、超时 ${toolStatusCount.timeout}`,
    `包含 ${trace.toolObservations.filter((item) => item.toolType === 'agent_call').length} 次子 Agent 调用`,
    `生成 ${trace.retrieverObservations.length} 条知识库检索记录${ragScenarioLabels.length ? `，覆盖 ${Array.from(new Set(ragScenarioLabels)).join('、')}` : ''}`,
    `实际产生 ${trace.scores.length} 个评分项`,
  ].join('；');

  function openChildTrace(targetAgentId?: string, childSessionId?: string, childTraceId?: string) {
    if (!targetAgentId || !childSessionId || !childTraceId) return;
    navigate(tracePathWithReturn({ tenantId, agentId: targetAgentId, sessionId: childSessionId, traceId: childTraceId }, { returnTo: `${location.pathname}${location.search}`, returnLabel: '返回父级 Trace' }));
  }

  const publicFilters = (filters: Record<string, string>) => Object.entries(filters).filter(([key]) => !['tenantId', 'siteId', 'agentId', 'environment'].includes(key));

  return <div className="min-h-full bg-slate-50 p-6"><div className="mx-auto max-w-[1700px] space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs text-slate-400"><button className="hover:text-blue-600" onClick={() => navigate(`/platform/agent-observability/tenants/${tenantId}`)}>{tenant.companyName}</button><span className="px-2">/</span><button className="hover:text-blue-600" onClick={() => navigate(`/platform/agent-observability/tenants/${tenantId}/agents/${agentId}`)}>{agent.agentName} Session</button><span className="px-2">/</span><button className="hover:text-blue-600" onClick={() => navigate(`/platform/agent-observability/tenants/${tenantId}/agents/${agentId}/sessions/${sessionId}`)}>{session.sessionId}</button><span className="px-2">/</span><span>{trace.traceId}</span></div><h1 className="mt-2 text-xl font-semibold text-slate-950">Trace 详情</h1><p className="mt-1 text-sm text-slate-500">当前轮次的完整对话、评分、运行、Tool、子 Agent 和知识库证据。</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => navigate(returnContext.returnTo)}>{returnContext.returnLabel}</Button>{trace.risk && <Button size="sm" onClick={() => navigate(`/platform/agent-observability/tenants/${tenantId}/agents/${agentId}/quality-reviews?traceId=${traceId}`)}>处理风险</Button>}</div></header>

    <ObservabilityRetentionNotice />

    <Card><CardHeader className="pb-3"><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle className="text-sm">基础标识与会话上下文</CardTitle><div className="flex gap-2"><Badge className={trace.status === 'completed' ? 'border-emerald-100 bg-emerald-50 text-emerald-700' : trace.status === 'timeout' ? 'border-amber-100 bg-amber-50 text-amber-700' : 'border-rose-100 bg-rose-50 text-rose-700'}>{trace.status === 'completed' ? '成功' : trace.status === 'timeout' ? '超时' : '异常'}</Badge>{feedbackBadge(trace.userFeedback)}</div></div></CardHeader><CardContent className="grid gap-x-6 gap-y-4 text-xs sm:grid-cols-2 lg:grid-cols-5"><div><span className="block text-slate-400">Session ID</span><strong className="mt-1 block break-all font-mono text-slate-700">{session.sessionId}</strong></div><div><span className="block text-slate-400">Trace ID</span><strong className="mt-1 block break-all font-mono text-slate-700">{trace.traceId}</strong></div><div><span className="block text-slate-400">用户 ID</span><strong className="mt-1 block font-mono text-slate-700">{session.userId}</strong></div><div><span className="block text-slate-400">创建 / 发生时间</span><strong className="mt-1 block text-slate-700">{session.startedAt} / {trace.occurredAt}</strong></div><div><span className="block text-slate-400">轮次 / 循环次数</span><strong className="mt-1 block text-slate-700">第 {trace.turnSeq} 轮 / {trace.loopCount} 次</strong></div><div className="sm:col-span-2"><span className="block text-slate-400">会话摘要</span><strong className="mt-1 block leading-5 text-slate-700">{sessionSummary}</strong></div><div><span className="block text-slate-400">Session 耗时 / 交互轮数</span><strong className="mt-1 block text-slate-700">{sessionDuration.toLocaleString()}ms / {traces.length} 轮</strong></div><div><span className="block text-slate-400">Session 质量 / 反馈</span><div className="mt-1 flex items-center gap-2"><strong className="text-slate-700">{sessionQuality === null ? '未评估' : scoreText(sessionQuality)}</strong>{feedbackBadge(sessionFeedback)}</div></div><div><span className="block text-slate-400">Session Tool / 子 Agent</span><strong className="mt-1 block text-slate-700">{sessionTools.length} 次 / {sessionTools.filter((item) => item.toolType === 'agent_call').length} 次</strong></div><div><span className="block text-slate-400">Session 知识库</span><strong className="mt-1 block text-slate-700">调用 {sessionRetrievers.length} 次 · 命中 {sessionRetrievers.filter((item) => item.hitCount > 0).length} 次</strong></div><div><span className="block text-slate-400">Trace 首响 / 总耗时</span><strong className="mt-1 block text-slate-700">{trace.firstResponseMs}ms / {trace.totalDurationMs}ms</strong></div></CardContent></Card>

    {trace.risk && <Card className="border-rose-200 bg-rose-50/40"><CardHeader className="pb-2"><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle className="text-sm text-rose-900">风险分析</CardTitle><div className="flex gap-2"><Badge className={RISK_CONFIG[trace.risk.riskLevel].cls}>{RISK_CONFIG[trace.risk.riskLevel].label}风险</Badge><Badge className={RISK_REVIEW_STATUS_CONFIG[trace.risk.reviewStatus].cls}>{RISK_REVIEW_STATUS_CONFIG[trace.risk.reviewStatus].label}</Badge></div></div></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-1">{trace.risk.sourceSignals.map((signal) => <Badge key={signal} className="border-rose-100 bg-white text-rose-700">{RISK_SOURCE_CONFIG[signal]}</Badge>)}</div><div className="grid gap-4 text-xs md:grid-cols-2 xl:grid-cols-4"><div><span className="text-slate-400">问题类型</span><strong className="mt-1 block text-slate-800">{trace.risk.issueType}</strong></div><div><span className="text-slate-400">风险评分</span><strong className="mt-1 block text-slate-800">{trace.risk.scoreName} · {scoreText(trace.risk.score)}</strong></div><div><span className="text-slate-400">原因归类</span><strong className="mt-1 block text-slate-800">{trace.risk.rootCause ?? '待人工质检'}</strong></div><div><span className="text-slate-400">质检评分</span><strong className="mt-1 block text-slate-800">{trace.risk.reviewScore == null ? '未质检' : `${trace.risk.reviewScore} / 5`}</strong></div></div><div className="grid gap-4 text-xs lg:grid-cols-3"><div><span className="text-slate-400">诊断</span><p className="mt-1 leading-5 text-slate-700">{trace.risk.diagnosis}</p></div><div><span className="text-slate-400">客户影响</span><p className="mt-1 leading-5 text-slate-700">{trace.risk.customerImpact}</p></div><div><span className="text-slate-400">期望行为</span><p className="mt-1 leading-5 text-slate-700">{trace.risk.expectedBehavior}</p></div></div>{trace.risk.reviewComment && <div className="rounded border border-rose-100 bg-white p-3 text-xs"><span className="text-slate-400">人工质检结论</span><p className="mt-1 leading-5 text-slate-700">{trace.risk.reviewComment}</p></div>}</CardContent></Card>}

    <Card className="border-blue-200 bg-blue-50/40"><CardHeader className="pb-2"><CardTitle className="text-sm text-blue-900">本轮执行总结</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-blue-900">{evidenceSummary}。</p><p className="mt-2 text-xs leading-5 text-blue-700">下方 Tool 与知识库列表直接给出成功、失败、超时、正常命中、未命中、低相关和部分有据等具体记录，供研发按字段实现。</p></CardContent></Card>

    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader className="pb-3"><CardTitle className="text-sm">用户输入</CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap break-words text-sm leading-6 text-slate-900">{trace.input}</p></CardContent></Card><Card><CardHeader className="pb-3"><CardTitle className="text-sm">Agent 回复</CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap break-words text-sm leading-6 text-slate-700">{trace.output}</p></CardContent></Card></div>

    <Card><CardHeader className="pb-3"><CardTitle className="text-sm">评分详情（{trace.scores.length}）</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>评分项</TableHead><TableHead>挂载位置</TableHead><TableHead>分数</TableHead><TableHead>原始分 / 范围</TableHead><TableHead>评分理由</TableHead></TableRow></TableHeader><TableBody>{trace.scores.length === 0 ? <TableRow><TableCell colSpan={5} className="py-8 text-center text-slate-400">该 Trace 没有评分记录。</TableCell></TableRow> : trace.scores.map((score, index) => { const metric = scoreCatalog.get(score.code); return <TableRow key={`${score.code}-${index}`}><TableCell><div className="font-medium">{metric?.nameZh ?? score.name}</div><div className="mt-1 text-xs text-slate-500">{metric?.name ?? score.name}</div><div className="mt-1 font-mono text-[11px] text-slate-400">{score.code}</div></TableCell><TableCell>{SCORE_SCOPE_LABEL[score.scope] ?? score.scope}</TableCell><TableCell className="font-semibold">{score.value === null ? '未评估' : scoreText(score.value)}</TableCell><TableCell>{score.rawScore === undefined ? '—' : String(score.rawScore)}<div className="mt-1 text-xs text-slate-400">{score.scoreRange ?? '—'}</div></TableCell><TableCell className="max-w-[520px] whitespace-pre-wrap text-xs leading-5 text-slate-600">{score.reason || '—'}</TableCell></TableRow>; })}</TableBody></Table></CardContent></Card>

    <Card><CardHeader className="pb-3"><CardTitle className="text-sm">生成运行</CardTitle></CardHeader><CardContent><dl className="grid gap-x-6 gap-y-4 text-xs sm:grid-cols-2 lg:grid-cols-6"><div><dt className="text-slate-400">Observation ID</dt><dd className="mt-1 break-all font-mono text-slate-700">{trace.generation.observationId}</dd></div><div><dt className="text-slate-400">状态</dt><dd className="mt-1 text-slate-700">{trace.generation.status}</dd></div><div><dt className="text-slate-400">首 Token</dt><dd className="mt-1 text-slate-700">{trace.generation.firstTokenMs}ms</dd></div><div><dt className="text-slate-400">生成耗时</dt><dd className="mt-1 text-slate-700">{trace.generation.durationMs}ms</dd></div><div><dt className="text-slate-400">输入 / 输出 Token</dt><dd className="mt-1 text-slate-700">{trace.generation.inputTokens.toLocaleString()} / {trace.generation.outputTokens.toLocaleString()}</dd></div><div><dt className="text-slate-400">成本</dt><dd className="mt-1 text-slate-700">¥{trace.generation.cost.toFixed(2)}</dd></div></dl></CardContent></Card>

    <Card><CardHeader className="pb-3"><CardTitle className="text-sm">Tool / 子 Agent（{trace.toolObservations.length}）</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table className="min-w-[1200px]"><TableHeader><TableRow><TableHead>Observation</TableHead><TableHead>Tool / 类型</TableHead><TableHead>完整输入</TableHead><TableHead>完整输出 / 错误</TableHead><TableHead>状态 / 耗时</TableHead><TableHead>Tool 评分（0–1）</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{trace.toolObservations.length === 0 ? <TableRow><TableCell colSpan={7} className="py-8 text-center text-slate-400">该 Trace 没有 Tool 调用。</TableCell></TableRow> : trace.toolObservations.map((tool) => <TableRow key={tool.observationId}><TableCell className="font-mono text-xs">{tool.observationId}</TableCell><TableCell><div className="font-medium">{tool.toolType === 'agent_call' ? `调用子 Agent：${tool.targetAgentName ?? tool.toolName}` : tool.toolName}</div><div className="mt-1 text-xs text-slate-400">{tool.toolType}</div>{tool.toolType === 'agent_call' && <div className="mt-2 text-[11px] text-slate-500">子 Session / Trace：{tool.childSessionId ?? '—'} / {tool.childTraceId ?? '—'}</div>}</TableCell><TableCell className="max-w-[320px] whitespace-pre-wrap break-words text-xs leading-5">{tool.inputSummary}</TableCell><TableCell className="max-w-[320px] whitespace-pre-wrap break-words text-xs leading-5">{tool.outputSummary}{tool.error && <div className="mt-2 text-rose-600">错误：{tool.error}</div>}</TableCell><TableCell><Badge className={tool.status === 'success' ? 'border-emerald-100 bg-emerald-50 text-emerald-700' : tool.status === 'timeout' ? 'border-amber-100 bg-amber-50 text-amber-700' : 'border-rose-100 bg-rose-50 text-rose-700'}>{TOOL_STATUS_LABEL[tool.status]}</Badge><div className="mt-1 text-xs text-slate-400">{tool.durationMs}ms</div></TableCell><TableCell className="min-w-[180px] text-xs"><div><span className="text-slate-400">工具选择：</span>{tool.selectionScore === null ? '未评估' : scoreText(tool.selectionScore)}</div><div className="mt-1"><span className="text-slate-400">动作对齐：</span>{tool.actionAlignmentScore === null ? '未评估' : scoreText(tool.actionAlignmentScore)}</div><div className="mt-1"><span className="text-slate-400">执行成功：</span>{tool.successScore === null ? '未评估' : scoreText(tool.successScore)}</div><div className="mt-1"><span className="text-slate-400">参数准确：</span>{tool.parameterAccuracyScore === null ? '未评估' : scoreText(tool.parameterAccuracyScore)}</div><div className="mt-2 text-[11px] leading-4 text-slate-400">分数越接近 1 越好；具体定义见产品方案 Tool 评分章节。</div></TableCell><TableCell className="text-right">{tool.toolType === 'agent_call' && tool.targetAgentId && tool.childSessionId && tool.childTraceId ? <Button size="sm" variant="outline" onClick={() => openChildTrace(tool.targetAgentId, tool.childSessionId, tool.childTraceId)}>查看子 Agent Trace</Button> : '—'}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>

    <Card><CardHeader className="pb-3"><CardTitle className="text-sm">知识库检索（{trace.retrieverObservations.length}）</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table className="min-w-[1100px]"><TableHeader><TableRow><TableHead>Observation</TableHead><TableHead>Query</TableHead><TableHead>TopK / 业务过滤</TableHead><TableHead>命中文档与切片</TableHead><TableHead>Query / Context / Groundedness</TableHead></TableRow></TableHeader><TableBody>{trace.retrieverObservations.length === 0 ? <TableRow><TableCell colSpan={5} className="py-8 text-center text-slate-400">该 Trace 未调用知识库。</TableCell></TableRow> : trace.retrieverObservations.map((item) => <TableRow key={item.observationId}><TableCell className="font-mono text-xs">{item.observationId}</TableCell><TableCell className="max-w-[280px] whitespace-pre-wrap break-words">{item.query}</TableCell><TableCell className="text-xs"><div>topK {item.topK}</div><div className="mt-1 whitespace-pre-wrap text-slate-400">{publicFilters(item.filters).map(([key, value]) => `${key}=${value}`).join('\n') || '无业务过滤条件'}</div></TableCell><TableCell className="max-w-[440px]"><div className="mb-2 flex items-center gap-2"><span>命中 {item.hitCount}</span><Badge className={retrieverScenario(item) === '正常命中' ? 'border-emerald-100 bg-emerald-50 text-emerald-700' : retrieverScenario(item) === '未命中' ? 'border-amber-100 bg-amber-50 text-amber-700' : 'border-rose-100 bg-rose-50 text-rose-700'}>{retrieverScenario(item)}</Badge></div>{item.hits.length === 0 ? <span className="text-xs text-amber-700">未命中</span> : <div className="space-y-2">{item.hits.map((hit) => <div key={`${hit.docId}-${hit.chunkId}`} className="rounded border border-slate-100 p-2 text-xs"><div className="font-medium">{hit.title}</div><div className="mt-1 font-mono text-slate-400">{hit.docId} / {hit.chunkId}</div><div className="mt-1">检索分 {scoreText(hit.score)}</div></div>)}</div>}</TableCell><TableCell className="text-xs"><div>Query {item.queryQualityScore === null ? '未评估' : scoreText(item.queryQualityScore)}</div><div className="mt-1">Context {item.contextRelevanceScore === null ? '未评估' : scoreText(item.contextRelevanceScore)}</div><div className="mt-1">Groundedness {item.groundednessScore === null ? '未评估' : scoreText(item.groundednessScore)}</div></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>

    <Card><CardHeader className="pb-3"><CardTitle className="text-sm">所属 Session 全部轮次（{traces.length}）</CardTitle></CardHeader><CardContent className="space-y-3">{traces.map((item) => <div key={item.traceId} className={`rounded-lg border p-4 ${item.traceId === trace.traceId ? 'border-blue-300 bg-blue-50/30' : 'border-slate-200'}`}><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><Badge className="border-slate-200 bg-white text-slate-600">第 {item.turnSeq} 轮</Badge><span className="font-mono text-xs text-slate-400">{item.traceId}</span>{feedbackBadge(item.userFeedback)}</div>{item.traceId !== trace.traceId && <Button size="sm" variant="outline" onClick={() => navigate(tracePathWithReturn({ tenantId, agentId, sessionId, traceId: item.traceId }, { returnTo: sessionPath, returnLabel: '返回 Session' }))}>查看该轮</Button>}</div><div className="mt-3 grid gap-4 lg:grid-cols-2"><div><div className="text-[11px] text-slate-400">用户输入</div><p className="mt-1 whitespace-pre-wrap break-words text-sm leading-6 text-slate-900">{item.input}</p></div><div><div className="text-[11px] text-slate-400">Agent 回复</div><p className="mt-1 whitespace-pre-wrap break-words text-sm leading-6 text-slate-700">{item.output}</p></div></div></div>)}</CardContent></Card>
  </div></div>;
}
