import { useMemo, useState } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { RISK_CONFIG, TOOL_TYPE_CONFIG, mockAgentListData, mockTenantListData } from './data';
import { handleFetchRiskSamples, handleFetchToolMetrics } from './actions';
import { getLowQualityToolCalls, getToolQualityAggregates, getToolQualityBreakdowns } from './observabilitySelectors';
import { tracePathWithReturn } from './routes';
import { metricTone, percentText, scoreText } from './shared';
import type { RiskLevel, TimeRange, ToolType } from './types';

function Score({ value, coverage, callCount }: { value: number | null; coverage: number; callCount: number }) {
  return <div className={value === null ? 'text-slate-400' : metricTone(value * 100, 80)}>{value === null ? '未评估' : scoreText(value)}<div className="mt-1 text-[11px] text-slate-400">{coverage} / {callCount}</div></div>;
}

export default function ToolObservabilityDetailPage() {
  const { toolType = '' } = useParams<{ toolType: ToolType }>();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [timeRange, setTimeRange] = useState<TimeRange>((searchParams.get('timeRange') as TimeRange) || '7d');
  const [riskLevel, setRiskLevel] = useState<RiskLevel | 'all'>((searchParams.get('riskLevel') as RiskLevel | 'all') || 'all');
  const config = TOOL_TYPE_CONFIG[toolType as ToolType];
  const stats = useMemo(() => getToolQualityAggregates(toolType as ToolType)[0], [toolType]);
  const rows = useMemo(() => getToolQualityBreakdowns(toolType as ToolType), [toolType]);
  const risks = useMemo(() => getLowQualityToolCalls(toolType as ToolType).filter((item) => riskLevel === 'all' || item.severity === riskLevel), [riskLevel, toolType]);
  const detailPath = `/platform/agent-observability/tools/${toolType}?riskLevel=${riskLevel}&timeRange=${timeRange}`;

  if (!config || !stats) return <div className="min-h-full bg-gray-50 p-6"><Card><CardContent className="pt-6">未找到该工具或其调用记录。</CardContent></Card></div>;

  return <div className="min-h-full space-y-5 bg-gray-50 p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h1 className="text-xl font-semibold text-gray-900">{config.label}</h1><Badge className="border-gray-900 bg-gray-900 text-white">工具详情</Badge></div><p className="mt-1 text-sm text-gray-500">所有指标均直接基于该 Tool 的 Observation 聚合；低质量调用必须满足失败、超时、低评分或明确的 Tool 风险关联条件。</p></div><div className="flex items-center gap-2"><Select value={timeRange} onValueChange={(value) => { const next = value as TimeRange; setTimeRange(next); handleFetchToolMetrics({ timeRange: next, toolType: toolType as ToolType }); }}><SelectTrigger className="h-8 w-28 bg-white text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="today">今天</SelectItem><SelectItem value="7d">近 7 天</SelectItem><SelectItem value="30d">近 30 天</SelectItem></SelectContent></Select><Button size="sm" variant="outline" onClick={() => navigate('/platform/agent-observability/tools')}>返回工具中心</Button></div></div>
    <div className="grid grid-cols-2 gap-4 xl:grid-cols-6"><Card><CardContent className="pt-4"><div className="text-xs text-gray-400">调用次数</div><div className="mt-1 text-2xl font-semibold">{stats.callCount}</div><div className="mt-1 text-xs text-gray-400">覆盖 {stats.traceCount} 条 Trace</div></CardContent></Card><Card><CardContent className="pt-4"><div className="text-xs text-gray-400">执行成功率</div><div className={`mt-1 text-2xl font-semibold ${metricTone(stats.successRate, 97)}`}>{percentText(stats.successRate)}</div><div className="mt-1 text-xs text-gray-400">{stats.successCount} / {stats.callCount}</div></CardContent></Card><Card><CardContent className="pt-4"><div className="text-xs text-gray-400">平均耗时</div><div className="mt-1 text-2xl font-semibold">{stats.avgDurationMs.toFixed(0)}ms</div></CardContent></Card><Card><CardContent className="pt-4"><div className="text-xs text-gray-400">Tool 选择</div><div className="mt-1 text-2xl font-semibold">{stats.selectionScore === null ? '未评估' : scoreText(stats.selectionScore)}</div><div className="mt-1 text-xs text-gray-400">已评估 {stats.selectionCoverage} / {stats.callCount}</div></CardContent></Card><Card><CardContent className="pt-4"><div className="text-xs text-gray-400">动作对齐</div><div className="mt-1 text-2xl font-semibold">{stats.actionAlignmentScore === null ? '未评估' : scoreText(stats.actionAlignmentScore)}</div><div className="mt-1 text-xs text-gray-400">已评估 {stats.actionAlignmentCoverage} / {stats.callCount}</div></CardContent></Card><Card><CardContent className="pt-4"><div className="text-xs text-gray-400">参数准确</div><div className="mt-1 text-2xl font-semibold">{stats.parameterAccuracyScore === null ? '未评估' : scoreText(stats.parameterAccuracyScore)}</div><div className="mt-1 text-xs text-gray-400">已评估 {stats.parameterAccuracyCoverage} / {stats.callCount}</div></CardContent></Card></div>
    <Card><CardHeader className="pb-2"><CardTitle className="text-sm">按客户与 Agent 查看</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><Table className="min-w-[1120px]"><TableHeader><TableRow><TableHead>公司租户</TableHead><TableHead>Agent</TableHead><TableHead>调用 / Trace</TableHead><TableHead>执行成功率</TableHead><TableHead>耗时</TableHead><TableHead>Tool 选择</TableHead><TableHead>动作对齐</TableHead><TableHead>参数准确</TableHead></TableRow></TableHeader><TableBody>{rows.map((row) => { const tenant = mockTenantListData.find((item) => item.tenantId === row.tenantId); const agent = mockAgentListData.find((item) => item.agentId === row.agentId); return <TableRow key={`${row.agentId}-${row.toolName}`}><TableCell>{tenant?.companyName ?? row.tenantId}</TableCell><TableCell><div>{agent?.agentName ?? row.agentId}</div><div className="mt-1 text-xs text-slate-400">{row.toolName}</div></TableCell><TableCell>{row.callCount} / {row.traceCount}</TableCell><TableCell className={metricTone(row.successRate, 97)}>{percentText(row.successRate)}</TableCell><TableCell>{row.avgDurationMs.toFixed(0)}ms</TableCell><TableCell><Score value={row.selectionScore} coverage={row.selectionCoverage} callCount={row.callCount} /></TableCell><TableCell><Score value={row.actionAlignmentScore} coverage={row.actionAlignmentCoverage} callCount={row.callCount} /></TableCell><TableCell><Score value={row.parameterAccuracyScore} coverage={row.parameterAccuracyCoverage} callCount={row.callCount} /></TableCell></TableRow>; })}</TableBody></Table></div></CardContent></Card>
    <Card><CardHeader className="flex-row items-center justify-between pb-2"><div><CardTitle className="text-sm">低质量调用</CardTitle><p className="mt-1 text-xs text-slate-500">仅展示具备直接证据的调用：失败/超时、低于 0.80 的评分，或明确归因为 Tool 的关联风险。</p></div><Select value={riskLevel} onValueChange={(value) => { const next = value as RiskLevel | 'all'; setRiskLevel(next); handleFetchRiskSamples({ timeRange, riskLevel: next }); }}><SelectTrigger className="h-8 w-28 bg-white text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">全部风险</SelectItem><SelectItem value="critical">严重</SelectItem><SelectItem value="high">高</SelectItem><SelectItem value="medium">中</SelectItem><SelectItem value="low">低</SelectItem></SelectContent></Select></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>风险 / 调用</TableHead><TableHead>用户问题</TableHead><TableHead>触发条件</TableHead><TableHead>直接证据</TableHead><TableHead>下一步动作</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{risks.length === 0 ? <TableRow><TableCell colSpan={6} className="py-10 text-center text-slate-400">当前筛选下没有具备直接证据的低质量调用。</TableCell></TableRow> : risks.map((item) => <TableRow key={item.tool.observationId}><TableCell><Badge className={RISK_CONFIG[item.severity].cls}>{RISK_CONFIG[item.severity].label}</Badge><div className="mt-2 font-mono text-[11px] text-slate-400">{item.tool.observationId}</div></TableCell><TableCell className="max-w-[240px]"><div className="line-clamp-2">{item.traceInput}</div><div className="mt-1 text-xs text-slate-400">{item.tool.toolName} · {item.tool.status}</div></TableCell><TableCell className="text-xs font-medium text-slate-700">{item.criterion}</TableCell><TableCell className="max-w-[260px] text-xs text-slate-500">{item.evidence}</TableCell><TableCell className="max-w-[260px] text-xs text-blue-600">{item.nextAction}</TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={() => navigate(tracePathWithReturn(item, { returnTo: detailPath, returnLabel: '返回工具详情' }))}>查看 Trace</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  </div>;
}
