// Shared agent + customer case data for all variants

const AGENTS = [
  {
    id: 'atlas',
    name: 'Atlas',
    cn: '数据分析',
    tag: '数据分析',
    desc: '自动化报表生成、SQL 查询、归因分析与异常监控',
    price: 0.012,
    calls: '2.4M',
    accuracy: 98.2,
    latency: 1.4,
    customers: 320,
    category: '数据分析 Agent',
    color: '#1f4ad3',
  },
  {
    id: 'cipher',
    name: 'Cipher',
    cn: '智能客服',
    tag: '客服销售',
    desc: '多语言客户对话、工单分派、SLA 实时监控与回访',
    price: 0.008,
    calls: '8.1M',
    accuracy: 96.4,
    latency: 0.9,
    customers: 540,
    category: '客服/销售 Agent',
    color: '#0a7c5a',
  },
  {
    id: 'forge',
    name: 'Forge',
    cn: '编程助手',
    tag: '研发提效',
    desc: '代码评审、重构建议、CI/CD 集成与缺陷定位',
    price: 0.015,
    calls: '1.2M',
    accuracy: 94.1,
    latency: 2.1,
    customers: 210,
    category: '编程 Agent',
    color: '#5c2bd6',
  },
  {
    id: 'quill',
    name: 'Quill',
    cn: '内容创作',
    tag: '营销内容',
    desc: '品牌文案、SEO 优化、多平台分发与素材改写',
    price: 0.006,
    calls: '4.7M',
    accuracy: 92.8,
    latency: 1.1,
    customers: 380,
    category: '内容创作 Agent',
    color: '#b8421a',
  },
  {
    id: 'loop',
    name: 'Loop',
    cn: '流程自动化',
    tag: '运营自动化',
    desc: '跨系统流程编排、定时任务、人机协作审批',
    price: 0.010,
    calls: '3.3M',
    accuracy: 99.1,
    latency: 0.6,
    customers: 290,
    category: '运营/自动化 Agent',
    color: '#0d5d8a',
  },
  {
    id: 'aegis',
    name: 'Aegis',
    cn: '合规法务',
    tag: '法律合规',
    desc: '合同审阅、风险条款识别、监管要点摘要',
    price: 0.022,
    calls: '0.4M',
    accuracy: 97.6,
    latency: 3.2,
    customers: 84,
    category: '垂直行业 Agent',
    color: '#3d3d3d',
  },
  {
    id: 'vital',
    name: 'Vital',
    cn: '医疗助理',
    tag: '医疗健康',
    desc: '病历结构化、诊疗辅助、循证文献检索',
    price: 0.018,
    calls: '0.7M',
    accuracy: 96.9,
    latency: 2.4,
    customers: 62,
    category: '垂直行业 Agent',
    color: '#0d7a6c',
  },
  {
    id: 'quant',
    name: 'Quant',
    cn: '金融研究',
    tag: '金融分析',
    desc: '财报解析、行业对比、组合风险压力测试',
    price: 0.020,
    calls: '0.9M',
    accuracy: 95.3,
    latency: 2.8,
    customers: 110,
    category: '垂直行业 Agent',
    color: '#7a4d0d',
  },
];

const CATEGORIES = [
  '客服/销售 Agent',
  '数据分析 Agent',
  '内容创作 Agent',
  '编程 Agent',
  '运营/自动化 Agent',
  '垂直行业 Agent',
];

const CASES = [
  {
    co: '中信资本',
    industry: '金融',
    agent: 'Quant',
    metric: '研究效率 +340%',
    quote: '过去 4 名分析师 1 周完成的行业对比研究,现在 1 天产出初稿。',
    saved: '¥ 2,800 万 / 年',
  },
  {
    co: '小马出行',
    industry: '出行',
    agent: 'Cipher',
    metric: '人工客服占比 64% → 18%',
    quote: '夜班排班直接砍掉,平均响应时间从 2 分钟降到 11 秒。',
    saved: '¥ 4,200 万 / 年',
  },
  {
    co: '联影医疗',
    industry: '医疗设备',
    agent: 'Vital',
    metric: '病历结构化 12 万份 / 月',
    quote: '医生从录入解放出来,临床科研产出翻倍。',
    saved: '720 名医生工时',
  },
  {
    co: '极氪汽车',
    industry: '智能制造',
    agent: 'Loop + Atlas',
    metric: '工单流转时间 -73%',
    quote: '把 11 个系统串成一条线,跨部门交付从天级到小时级。',
    saved: '¥ 1,600 万 / 年',
  },
];

const STATS = [
  { k: '入驻 Agent', v: '320+', sub: '覆盖 18 个行业场景' },
  { k: '月调用量', v: '21.8 亿', sub: '同比增长 412%' },
  { k: '企业客户', v: '2,400+', sub: '含 73 家世界 500 强' },
  { k: '平均响应', v: '0.9s', sub: 'P99 < 2.4s' },
];

window.AGENTS = AGENTS;
window.CATEGORIES = CATEGORIES;
window.CASES = CASES;
window.STATS = STATS;
